export const content = {
  he: {
    dir: 'rtl',
    lang: 'he',
    name: 'דור זיו',
    navItems: ['בית', 'הגישה', 'למי מתאים הטיפול?', 'שאלות נפוצות', 'מן השדה', 'אודותיי', 'קשר', 'נגישות'],
    langToggle: 'EN',

    home: {
      subtitle: 'פסיכותרפיה גופנית · בית אורן · אונליין',
      poemLines: `ליבי כל כך קטן,\nהוא כמעט בלתי נראה.\nכיצד יכול אתה לאכסן בתוכו צער כה רב?\n״הבט״, הוא ענה,\n״עיניך קטנות אף יותר,\nובכל זאת - הן מכילות את העולם״`,
      poemAuthor: '— ג׳לאל א-דין רומי',
      btn1: 'למי מתאים הטיפול?',
      btn2: 'אודותיי',
      btn3: 'יצירת קשר',
    },

    approach: {
      title: 'גישה שמחברת חיים',
      intro: 'גישת הביוסינתזה היא שיטת טיפול בינלאומית מעולם הפסיכותרפיה הגופנית, שנוסדה בשנות השבעים על ידי החוקר והתרפיסט דייוויד בואדלה. משמעות השם היא ״אינטגרציה של חיים״. נולדה מתוך תפיסה הומניסטית הרואה באדם שלם ומבקשת לחבר בין שלושת ממדי הקיום שלנו: הגופני, הרגשי והרוחני. הגישה זכתה להכרה רשמית מטעם האיגוד האירופי לפסיכותרפיה (EAP) ופועלת תחת הסטנדרטים של האיגוד האירופי לפסיכותרפיה גופנית (EABP).\n\nהבסיס של הביוסינתזה משלב ערוצי מחקר וטיפול קלאסיים ומודרניים. היא יונקת מפסיכותרפיית הגוף האנליטית ומשלבת עקרונות של פסיכולוגיית המעמקים, תיאוריית יחסי אובייקט ופסיכולוגיה טרנספרסונלית. בואדלה ביסס את השיטה על תהליכי ההתפתחות הראשוניים ברחם (אמבריולוגיה), מתוך הבנה שניתן לעבוד כמבוגרים על רישומים שהחלו כבר בשלבים מוקדמים אלו והתעצבו לאורך השנים. כיום, מחקרים עדכניים מראים כיצד הסומה (הגוף) משפיע ומושפע ישירות דרך נשימה, תנועה, מגע וקשר מבוסס אמון.\n\nייחודה של הביוסינתזה בקליניקה טמון בהיותה ממוקדת במשאבים, בניית קשר מבוסס אמון ואיתור של הנתיב הפתוח עבור האדם ולא להתאימו אליה, מתוך כבוד וסקרנות למערכת שלו. אנו מניחים שמשברים ואירועי החיים הותירו בגוף דפוסים שהגנו ושמרו בעבר, אך כעת חוסמים את החיוניות והחיוּת. העבודה המשותפת מסייעת למערכת שלך לנוע מתוך המצוקה אל עבר כוחות טבעיים שבך. יחסים שיש בהם אמון וביטחון, המאפשרים לחוות חוויות מתקנות וחדשות מיטיבות, יכולים להביא לשינוי יציב ביומיום - מבלי לפרוץ הגנות באופן אגרסיבי, מבלי לנסות "לתקן" בצורה מכנית את מה שמרגיש שבור, ומבלי לפתוח פצעים בצורה מכאיבה או מציפה.',
      streams: [
        { title: 'קרקע ותנועה', body: 'ביסוס תחושת קרקע ויציבות גופנית כמקור ישיר לוויסות רגשי ותחושת ביטחון ומקום בעולם. ערוץ זה מתמקד בשחרור דפוסי מתח, נוקשות וקיפאון כרוניים בשרירים ובשלד, שהצטברו במערכת בעקבות דחק מתמשך או אירועי קיצון וטראומה, ומשיב לגוף את חופש התנועה והחיוניות שלו.' },
        { title: 'רגש ונשימה', body: 'חיבור למקצב הפנימי, ויסות והכלה של רגשות ותחושות אינטנסיביות באמצעות הנשימה. עבודה זו מעניקה תמיכה עמוקה למערכת העצבים, ומאפשרת מעבר ממצבי הצפה או אדישות אל מרכז פנימי יציב ומווסת.' },
        { title: 'מחשבות ותשומת לב', body: 'פיתוח קשב סקרן, חקירה ובהירות מנטלית כלפי המורכבות של התודעה והקשרי העולם שלך. תרגום עדין של תחושות ורגשות למילים בהירות בעלות משמעות, כדי ליצור אינטגרציה שלמה, לחבר בין הראש לגוף ולאפשר גישה אל המהות האותנטית היחודית לך.' },
      ],
      quote: { text: 'כיצד נוכל לארוג יחד את שלושת הממדים היסודיים של הקיום האנושי: הקיום הגופני שלנו, החוויה הפסיכולוגית, והמהות הרוחנית?', author: '— דיוויד בואדלה, ״זרמי חיים״' },
    },

    forWho: {
      title: 'למי מתאימה פסיכותרפיה גופנית?',
      intro1: 'פסיכותרפיה גופנית מציעה חוויה בה מעבר לדיבור נתייחס לכל מה שמתרחש בגוף שמשמש כשותף מלא בתהליך של עיבוד, איזון וויסות. קשר שנבנה בו אמון, קשב למתרחש בגוף ובמרחב ולרצונות העמוקים והמהותיים שנובעים בו, תנועה בכיוונים הפתוחים מאפשרים להתקדם במקום שהמילים לבדן לפעמים אינן יכולות להגיע אליהם.',
      intro2: 'הטיפול מתאים לכל מי שמרגיש שתופעות רגשיות, מנטליות או פיזיות שונות מנהלות אותו בעקבות חוויות קשות ואירועי חיים. בין אם מדובר באירוע חד-פעמי חריף או בהתמודדות מתמשכת; בין אם זה קרה בשלב מוקדם או מאוחר בחיים; ובין אם הסיבה לתחושות האלו ידועה וברורה לך לחלוטין או שנותרה עמומה, מבלבלת ולא מוסברת.',
      challengesTitle: 'האתגרים שאנו פוגשים בקליניקה',
      challengesSub: 'אם הגוף או הנפש אותתו לך שהגיע הזמן לעצור ולברר או להעמיק, אלו האתגרים והנושאים המרכזיים להם ניתן לתת מענה:',
      dailyLabel: 'איך זה יכול להחוות ביום יום?*',
      disclaimer: '* משתנה מאדם לאדם.',
      notFound: 'אם לא מצאת את הנושא שלך בכתוב מעלה, ניתן לכתוב בפנייה ונברר יחד.',
      processTitle: 'מבנה התהליך וציפיות',
      process1: 'אם זו הפעם הראשונה שבה הגעת למרחב של טיפול, חשוב לדעת שכל תהליך הוא ייחודי, מותאם אליך ואל הצרכים שלך באופן אישי. בהתאם לאתגר או לנושא, הטיפול יכול להיות קצר מועד (חצי שנה) או ארוך טווח.',
      process2: 'הגישה שמנחה אותי מבוססת על בניית קשר טיפולי שיש בו אמון, כבוד וסקרנות. יחד, ולעיתים באומץ, נפעל להשגת המטרות איתן הגעת. המפגש הראשון והבאים אחריו הם הזדמנות להיכרות ראשונית, לשאילת שאלות, ולבדיקה משותפת האם העבודה יחד מרגישה נכונה ומתאימה עבורך.',
      quote: { text: 'אולי זה לא סיפור שמח. אבל הוא אמיתי והוא שלי', author: '— מתוך הספר ״ירושה רגשית״ מאת גלית אטלס' },
      ctaText: 'לבחור בטיפול משמעו לעשות צעד לקראת קיום אנושי מלא ונוכח — מתוך הבנה שלהיות אדם בוגר בעולם זהו תהליך שלוקח זמן, הסכמה וחניכה.',
      ctaBtn: 'יצירת קשר',
      challenges: [
        { num: '1', title: 'לחץ, חרדה ודריכות יתר', body: 'כשהמערכת העצבית פועלת בעומס יתר ממושך או נושאת רישום של אירוע סוער מן העבר, החרדה והדריכות מפסיקות להיות רק "מחשבה" והופכות למצב קיומי קבוע המנהל את הגוף.', daily: 'חוסר שקט פנימי כרוני, בהלה עוצמתית מרעשים או גירויים קטנים, כתפיים מורמות ונוקשות, נשימה קצרה או שטחית, דפיקות לב מואצות, תחושת איום, הצפה פתאומית או מועקה בבית החזה המקשים על היכולת להרפות, להירגע ולישון.' },
        { num: '2', title: 'דכדוך, נסיגה וחוסר חיוניות', body: 'לעיתים, כדי להגן על עצמנו מכאב, פחד או מהצפה שהיו גדולים מכפי שהמערכת יכלה לשאת, הגוף והנפש נוקטים בצמצום ונסיגה, מה שמוביל תחושה של תקיעות והפחתת תחושת חיוניות טבעית.', daily: 'תחושת ריקנות, כובד פיזי כהה בגפיים (כאילו נדרש מאמץ עצום רק כדי להזיז את הגוף), נטייה להתנתק מהסביבה או מהגוף ברגעי מתח (דיסוציאציה), קהות רגשית וחושית, חוסר חום פיזי, מבט או יציבה רופסים או עמומים.' },
        { num: '3', title: 'אבל ואובדן', body: 'צער עמוק ואובדן של אדם קרוב, מערכת יחסים או שלב משמעותי בחיים, המתרחש בסביבה ובעולם, משנים את המערכת שחיים בה. לעיתים קשה לגעת בתכנים האלו והם מרגישים נפיצים או מסוכנים.', daily: 'תחושת ריקנות, כובד פיזי בלב או בגפיים, שאלות קיומיות, חוסר משמעות או ערך, חוויה של זמן קופא בעוד העולם ממשיך לנוע כרגיל, קושי לבכות או להרגיש רגשות.' },
        { num: '4', title: 'קשיים במערכות יחסים, גבולות וקשר', body: 'האופן שבו אנחנו מתקשרים עם העולם קשור ישירות לגבולות הגופניים והאנרגטיים שלנו. ליכולת להישאר בקשר עם עצמנו בזמן שבקשר עם אחר, במיוחד אם הגבולות הללו נפרצו או נפגעו בעבר.', daily: 'תחושה של "היבלעות", דריכות גבוהה או תחושה של ׳אני נעלם׳ בתוך זוגיות או מול סמכות, קושי פיזי להגיד "לא" (הרגשה של מחנק או כיווץ בגרון), או לחלופין בניית חומות נוקשות ומשוריינות שמובילות לבדידות.' },
        { num: '5', title: 'תופעות רגשיות וגופניות', body: 'פעמים רבות הגוף "מדבר" ומנציח תאונות, פציעות או חוויות רגשיות קשות מן העבר דרך סימפטומים, כאבים כרוניים או תחושות מצוקה משתנות, מבלי שיש להם פתרון או הסבר רפואי ברור.', daily: 'כאבים שהוגדרו פסיכוסומטיים, תופעות גופניות שלא חולפות, שינוי משמעותי בתחושת העצמי, חוסר תחושה, חוויות של פלאשבקים.' },
        { num: '6', title: 'משברי חיים ומשברים רפואיים', body: 'מפגש פתאומי עם חולי, פציעה, או שינוי דרמטי במצב הבריאותי, מייצר לעיתים טראומה רפואית המטלטלת את תחושת השליטה והביטחון הבסיסית בעולם ומציף שאלות קיומיות גדולות.', daily: 'חוויה עמוקה של בגידת הגוף, פחד קיומי מהעתיד, חוסר אונים בתפקוד הגוף, קושי ומתח בהסתגלות למגבלות חדשות שנכפו על ידי תאונה, פציעה או מחלה.' },
        { num: '7', title: 'צמיחה, העמקה וחיבור לחיוּת', body: 'פנייה לטיפול לא חייבת לנבוע רק מתוך שבר חריף. לעיתים הדחף להתחיל תהליך מגיע מתוך רצון פנימי עמוק להאט את הקצב האוטומטי של החיים, להכיר את עצמך ולחיות חיים מלאים יותר.', daily: 'תחושה עמומה של תקיעות ביומיום, "אוטומט" קבוע ותחושת חוסר חיוניות, לצד דחף פנימי שקט המבקש להעמיק, לחקור, ללכת אחר דחף וסקרנות טבעיים. רצון לחיבור לסמכות פנימית ויציבות בעולם.' },
      ],
    },

    faq: {
      title: 'שאלות נפוצות',
      quote: { text: 'ואם אוכל לנסות ולסכם מהי עמדה טיפולית, הרי שחלק ניכר ממנה הוא ללמד אותך להיות מאוד מכבד כלפי המורכבות של המיינד שלך; להבין שהוא לא בדיוק דבר שברור לך מאליו', author: '— תרגום לא מדויק של מילותיו של אלן דה בוטון, סביב השאלה למה בכלל להגיע לטיפול, מתוך ראיון בהשתתפותו' },
      items: [
        { q: 'מה זה בכלל פסיכותרפיה גופנית?', a: 'פסיכותרפיה גופנית (ובפרט גישת הביוסינתזה) יוצאת מנקודת הנחה שהגוף והנפש הם יחידה אחת. לדוגמה, כשמישהו עושה משהו שגורם לנו לכעוס, אנו נוטים לחשוב על כך שהוא מעצבן, לא מצליחים להתמקד בדבר אחר ובמקביל מרגישים חום ומתח גבוה מתפשטים בגוף.\n\nאירועי עבר והווה, משברים ומתחים אינם נשמרים רק כזיכרון מנטלי, אלא מותירים רישום במערכת העצבים, ברקמות השרירים ובדפוסי הנשימה. במפגשים, לצד השיחה והקשר הנבנה, אנו מפנים קשב למה שמתרחש מתחת למילים. דרך נשימה, דמיון, תנועה ולעיתים מגע, אנו מגלים את הנתיב שנגיש וזמין עבורך, ומגיעים למקומות שהדיבור לבדו אינו יכול להגיע אליהם.' },
        { q: 'האם הטיפול מחייב מגע?', a: 'חד-משמעית לא. גישת הביוסינתזה מאפשרת שימוש במגע מושכל ומכבד ככלי לעבודה, אך זה אינו תנאי הכרחי להצלחת התהליך, כפי שניתן ללמוד גם מתהליכים טיפוליים שלמים שנעשו אונליין. כל עבודה הכוללת מגע נעשית אך ורק בהסכמה מלאה ומפורשת שלך, ותלויה לחלוטין בהעדפה האישית ובגבולות של שני הצדדים במפגש. אם קיימת רתיעה או העדפה לעבוד ללא מגע כלל, התהליך יתבצע באופן מלא דרך שיחה, קשב, נשימה ותנועה במרחב החדר.' },
        { q: 'איך נראה מפגש טיפולי בקליניקה באופן מעשי?', a: 'למפגש אין פרוטוקול נוקשה. בשיח ובהקשבה אפשר לגשת לנושאים איתם הגעת באותו היום, או להמשיך ולהעמיק בנושא שנגענו בו לאורך זמן. מתוך השיח ודרך גישת הביוסינתזה – נברר, נחקור, נשאל, נבדוק, נתנסה ונגלה מה מבקש את תשומת הלב שלך.\n\nבהתאם לכך, נפגוש יחד שאלות פתוחות, פחדים עתיקים, גילויים מרגשים, דפוסים שמשתחזרים, כאבים שעוד כואבים וכאלו שהחלימו, לצד תנועות מעניינות וחדשות. אנו מתקדמים בקצב שמתאים למערכת שלך, מבלי לייצר הצפה או דחיפה מעבר לגבולות היכולת שלך. אנחנו לא פורצים הגנות.' },
        { q: 'כמה זמן נמשך הטיפול ומה ההבדל בין תהליך קצר לתהליך ארוך?', a: 'משך התהליך נגזר ישירות מהבקשה ומהמטרות איתן הגעת, ואנו מתאמים ציפיות סביבו כבר במפגשים הראשונים:\n\nתהליך ממוקד וקצר מועד (עד חצי שנה): מתאים בדרך כלל סביב התמודדות עם משבר נקודתי, שינוי פתאומי או צומת חיים ספציפי. המיקוד הוא ברכישת כלים סומטיים מעשיים לוויסות, ביסוס עוגנים והחזרת תחושת קרקוע וביטחון.\n\nתהליך מעמיק וארוך טווח (שנה ומעלה): מתאים כאשר הבקשה נוגעת בדפוסים כרוניים מתמשכים, אירועים דרמטיים שהותירו חותם משמעותי, טראומה מורכבת, קשיים עמוקים במערכות יחסים, או רצון עמוק בחקירה עצמית.\n\nהתהליך מסתיים לבקשתך וכשיש תחושת מוכנות, ותמיד מתוך חשיבה ושיח משותפים.' },
        { q: 'מה קורה במפגש הראשון?', a: 'המפגש הראשון מוקדש להיכרות ראשונית ולהתחלת בניית מרחב שמור. זוהי הזמנה עבורך להביא את הסיפור שלך, להעלות שאלות וחששות ולשתף באתגרים שהובילו אותך לפנות לטיפול. עבורי, זו הזדמנות להיחשף ולהקשיב לעולם שלך, להציע הצעות ולבחון יחד איתך האם הגישה הטיפולית שלי יכולה להתאים לך.\n\nאין שום מחויבות להמשך תהליך בעצם ההגעה למפגש זה, אך אני מציע שנתייחס לארבעת המפגשים הראשונים כמהלך המיועד ליצירת קשר, ביסוס אמון ובדיקה הדדית.' },
        { q: 'מהי גישת ביוסינתזה (Biosynthesis) והאם היא מוכרת מבחינה מקצועית?', a: 'ביוסינתזה היא גישה ותיקה ומוכרת של פסיכותרפיה גופנית-אנליטית, שנוסדה לפני למעלה מ-45 שנים על ידי דייוויד בואדלה. משמעות השם היא "אינטגרציה של חיים" והיא מבוססת על יצירת חיבור מחודש ואיזון בין שלושת ממדי הקיום היסודיים שלנו: הקיום הגופני, החוויה הפסיכולוגית והמהות הרוחנית.\n\nהגישה נשענת על מחקרים מבוססי מדע בתחומי הנוירוביולוגיה והאמבריולוגיה (התפתחות העובר). היא מוכרת באופן רשמי על ידי האיגוד האירופי לפסיכותרפיה (EAP) והאיגוד האירופי לפסיכותרפיה גופנית (EABP). למדתי בישראל בביה״ס לפסיכותרפיה בגישת הביוסינתזה, והתעודה שלי הוסמכה מטעם המכון הבינלאומי לביוסינתזה בשוויץ (IIBS). העבודה הקלינית שלי מתבצעת תחת הדרכה מקצועית קבועה.' },
        { q: 'ראיתי שאתה עוסק גם בטקסי אבל קהילתיים. איך זה קשור לקליניקה הפרטנית?', a: 'אבל וצער אינם פתולוגיה, ״מחלה״ או בעיה שיש לתקן או להעלים. הם חלק בלתי נפרד מהיותנו בעולם כבני אנוש מתבגרים, צומחים ונחנכים.\n\nהזיקה שלי לעולמות האלו מרחיבה את המבט בתוך החדר: התהליך הטיפולי מחובר תמיד להקשרים הרחבים של החיים - מההיסטוריה המשפחתית, מהתרבות וממערכות היחסים שעיצבו אותך. החיבור בין הטכנולוגיה הטקסית לבין העבודה הסומטית מאפשר לנו להעניק לצער וכאב ״צורה בעולם״, כפי שעשו בני אדם מאז ומתמיד.' },
      ],
    },

    writings: {
      title: 'השראה עונתית שנאספה או נכתבה',
    },

    about: {
      title: 'אודותיי',
      paragraphs: [
        'שלום, אני דור. השם שבחרתי לקליניקה, "להיות אדם", נולד מתוך התבוננות ארוכה על כך שלהיות אדם בוגר בעולם הזה הוא תהליך מתמשך, הלוקח זמן, דורש חניכה ומכיל בתוכו מגוון רחב של חוויות. המהלך המקצועי שלי בא לעולם מתוך מחקר ועיבוד אישי ומקצועי עמוק שהחל לפני כ-11 שנים, והוביל אותי לחקור דרכים בהן הגוף והנפש נפגשים וקשורים. לאחר שירות צבאי משמעותי יצאתי למסע חקירה, גילוי והתנסות.',
        'מאז שנת 2017 אני מלווה בקליניקה מבוגרים בתהליכי שינוי, התמודדות וצמיחה מתוך משבר באופן פרטני, פנים אל פנים ואונליין. דרכי המקצועית החלה דרך עבודה עם יוגה טיפולית (בהמשך שימשתי גם כעוזר הוראה בהכשרת מטפלים ומורים בתחום). התמחיתי ועבדתי בשיקום פגיעות ופציעות, כאבים כרוניים, מחלות אוטואימוניות, וויסות רגשי וגופני.',
        'החל משנת 2022 אני מטפל כפסיכותרפיסט גופני בגישת ביוסינתזה, מוסמך מטעם המכון הבינלאומי בשוויץ (IIBS). החיבור שלי לביוסינתזה נבע מכך שהיא מתאימה את עצמה לאדם, ולא להפך. היא מבוססת על יצירת איזון מחדש בין חלקים שונים בך, ומאפשרת לנוע מתוך מצוקה אל עבר משאבים טבעיים וחיוניוּת. כיום אני חלק מסגל ההוראה כעוזר הוראה בבית הספר לביוסינתזה בישראל ולאחרונה התחלתי את הכשרת המדריכים (Supervisors) בגישה. התהליך הטיפולי איתי בקליניקה הפרטית מתנהל תחת הדרכה מקצועית קבועה, במסגרת של תהליכים מעמיקים ארוכי טווח.',
        'העבודה שלי בחדר הטיפולים מחוברת להקשרים הרחבים של החיים. בטיפול אנו לוקחים בחשבון את הסיפור האישי והקשרי חייך, מתוך הבנה שאנחנו תמיד קשורים לאנשים, לסיפורים ולמקומות שעיצבו אותנו, גם אם אנחנו או הם כבר לא שם. תפיסה זו מלווה אותי גם באופן אישי: בעשור האחרון אני חוקר ובונה את הסיפור המשפחתי של אבותיי שמגיע ממזרח אירופה באמצעות איתור מסמכים בארכיבים ובעבודה דרך קונסטלציה משפחתית.',
        'המבט הרחב והזיקה הזו אל השורשים מהם צומחים אנשים הובילו אותי אל עולמות התוכן של טקסי אבל, חיים ומוות. הוסמכתי כמנחה בתוכנית "אבל כשער לחיים" בהשראת עבודתו של פרנסיס וולר (Francis Weller), ואני שואב השראה קבועה ממשנתם של סטיבן ג׳נקינסון (Stephen Jenkinson) ואלחנדרו חודורובסקי (Alejandro Jodorowski). כיום אני פועל כאיש צוות בטקסי אבל קהילתיים, מתוך הבנה שצער ואבל אינם פתולוגיה שיש לתקן, אלא חלק בלתי נפרד מתהליך של חניכה והבשלה אנושית. בעיניי, טקסים הם טכנולוגיות אנושיות הכרחיות לזמננו.',
        'לאורך השנים יזמתי והקמתי מיזמים המשלבים גוף וקהילה: הקמתי את "זוּזוּ" – מרחב לאירועי תנועה אלטרנטיביים המאפשר ביטוי אישי חופשי, והייתי מייסד-שותף של "Bodyfulness" (מיזם Wellness לארגונים).',
        'מחוץ לקליניקה, החקירה העצמית שלי מלווה בחיבור יומיומי לאדמה וליצירה: אני לומד על חיבור לאדמה דרך לימודי חקלאות יצרנית בקנה מידה קטן, מתסיס ירקות ומשמר מזון, חוקר תנועה ממוקדת ברקמת הפאשיה ומוצא עוגן והשראה במוזיקה, שירה ובשפת האחרוּת המופלאה - בה ולידה אנחנו חיים.',
        'אל המפגשים הטיפוליים אני מביא איתי איכויות של הקשבה עמוקה, נוכחות, סקרנות, הבחנה והומור. הכוונה המרכזית שמנחה אותי היא לבנות יחד איתך יחסים טיפוליים שיש בהם מפגש אנושי בגובה העיניים, אמון הדדי, כבוד, וקצב מדויק שמתאים לך ולהקשרים הייחודיים של חייך.',
      ],
      quote: { text: 'חשבתי שאני רוצה להיות משורר, אבל בעומק ליבי — רציתי פשוט להיות שיר.', author: '— חיימה גיל דה בידמה' },
    },

    contact: {
      title: 'דרכים ליצירת קשר',
      nameLbl: 'שם',
      namePh: 'השם שלך',
      phoneLbl: 'טלפון',
      phonePh: 'מספר הטלפון שלך',
      emailLbl: 'אימייל',
      emailPh: 'כתובת המייל שלך',
      msgLbl: 'הודעה',
      msgPh: 'במה אוכל לעזור?',
      sending: 'שולח...',
      send: 'שליחה',
      successTitle: 'ההודעה נשלחה, תודה!',
      successSub: 'אחזור אליך בהקדם.',
      contactMethodsLabel: 'דרכים נוספות לקשר',
      calendlyBtn: '📅 לבחירת מועד ביומן הדיגיטלי',
      waBtn: '💬 לשליחת הודעה בווטסאפ',
      locationLabel: 'פרטי מיקום',
      locationText: 'הקליניקה ממוקמת בבית אורן. בהגעה למפגש הראשון אנחה אותך היכן לחנות ואיפה ממוקמת בדיוק.',
    },

    accessibility: {
      title: 'נגישות במרחב הטיפולי',
      intro: 'חלק בלתי נפרד מיצירת מרחב טיפולי בטוח ומזמין לכל אחד, הוא השאיפה לאפשר גישה מלאה ומותאמת לצרכים השונים של המגיעים לקליניקה.',
      s1Title: 'גישה פיזית ומרחבית',
      s1p1: 'מיקום וגישה: הקליניקה בבית אורן ממוקמת בקומת קרקע, עם גישה ישירה וללא מדרגות. המרחב נגיש ומותאם למשתמשים בכיסאות גלגלים.',
      s1p2: 'חניה: בקרבת כניסת המבנה (60-70 מ) קיימת חניה ייעודית לאנשים עם מוגבלות.',
      s1p3: 'אם יש לך צורך בהסדרת הנגשה פיזית ספציפית או בליווי בעת ההגעה, אבקש ליצור איתי קשר מראש כדי שנוכל להיערך לכך בצורה המיטבית.',
      s2Title: 'התאמות וצרכים מיוחדים',
      s2p1: 'אם קיימות מוגבלויות ראייה, שמיעה, רגישויות סנסוריות או צרכים מיוחדים אחרים שלא צוינו כאן, אני מזמין אותך לציין זאת כבר בפנייה הראשונית או במהלך שיחת הטלפון שלנו, על מנת שנוכל להתאים את אופי המפגש והמרחב עבורך.',
      s3Title: 'אפשרות למפגשים מרחוק (טיפול אונליין)',
      s3p1: 'עבור אנשים המתמודדים עם מגבלות ניידות, קשיי נסיעה, או עבור מי שמתגוררים במרחק (כולל תושבי חוץ), נמצאים בתקופות מעבר וטיולים, או פשוט מעדיפים את להיפגש בסביבתם הביתית - ניתן לקיים את התהליך הטיפולי באופן מלא באונליין.',
      s3p2: 'תנאים נדרשים: כדי לאפשר את העבודה, יש צורך במחשב עם מצלמה וחיבור אינטרנט תקין ויציב, לצד סביבה שקטה, נעימה ובטוחה שבה ניתן לדבר ולנוע בחופשיות ללא הפרעה.',
      ctaTitle: 'יצירת קשר והתייעצות',
      ctaText: 'אם יש לך צרכים מיוחדים או שאלות בנושאי נגישות שלא קיבלו מענה בעמוד זה, אנא אל תהסס לפנות אליי בשיחה או בהודעה עם פירוט הנקודות החשובות לך. אני שוקד על הכנת מרחב טיפולי שמור ונגיש לכל אחד ויחד נבין כיצד לייצר מענה מתאים עבורך.',
    },
  },

  en: {
    dir: 'ltr',
    lang: 'en',
    name: 'Dor Ziv',
    navItems: ['Home', 'The Approach', 'Who Is It For?', 'FAQ', 'From the Field', 'About', 'Contact', 'Accessibility'],
    langToggle: 'עב',

    home: {
      subtitle: 'Somatic Psychotherapy · Beit Oren · Online',
      poemLines: `My heart is so small,\nit's almost invisible.\nHow can you place such big sorrows in it?\n"Look," he answered,\n"your eyes are even smaller,\nyet they behold the world."`,
      poemAuthor: '— Jalal al-Din Rumi',
      btn1: 'Who Is It For?',
      btn2: 'About Me',
      btn3: 'Contact',
    },

    approach: {
      title: 'A Perspective That Connects Life',
      intro: 'Biosynthesis is an internationally recognized somatic psychotherapy method, founded in the 1970s by researcher and therapist David Boadella. The name means "integration of life." It emerged from a humanistic vision of the human being as whole, seeking to reconnect the three dimensions of our existence: the physical, the emotional, and the spiritual. The approach has been officially recognized by the European Association for Psychotherapy (EAP) and operates under the standards of the European Association for Body Psychotherapy (EABP).\n\nThe foundations of Biosynthesis draw on both classical and current streams of research and practice. It is rooted in analytic body psychotherapy and integrates principles from depth psychology, object relations theory, and transpersonal psychology. Boadella grounded the method in early developmental processes in the womb (embryology), from the understanding that as adults we can work with imprints that began in these early stages and shaped us across the years. Today, current research shows how the soma (the body) influences and is influenced directly through breath, movement, touch, and trust-based relationship.\n\nWhat makes Biosynthesis distinctive in clinical practice is its resource-focused orientation: building a trust-based relationship and finding the open pathway for the person — rather than fitting them to the method — with respect and curiosity toward their system. We hold that crises and life events have left patterns in the body that once protected and preserved, but now block vitality and aliveness. The shared work helps your system move from distress toward the natural strengths within you. Relationships that hold trust and safety, enabling new and corrective experiences, can bring about stable change in daily life — without breaking through defenses aggressively, without trying to mechanically "fix" what feels broken, and without opening wounds in a painful or overwhelming way.',
      streams: [
        { title: 'Ground & Movement', body: 'Establishing a sense of physical grounding and stability as a direct source of emotional regulation and a felt sense of safety in the world. This channel focuses on releasing chronic patterns of tension, rigidity, and freeze held in the muscles and skeleton — accumulated through prolonged stress or extreme events and trauma — and restoring the body\'s natural freedom of movement and vitality.' },
        { title: 'Emotion & Breath', body: 'Connecting with the internal rhythm, regulating and containing intense emotions and sensations through the breath. This work offers deep support to the nervous system, enabling a transition from states of flooding or numbness toward a stable, regulated inner center.' },
        { title: 'Thought & Attention', body: 'Developing curious attention, inquiry, and mental clarity toward the complexity of consciousness and your relational world. A gentle translation of sensations and emotions into clear, meaningful words — to create wholeness, to bridge head and body, and to allow access to your authentic, unique essence.' },
      ],
      quote: { text: 'Biosynthesis means "integration of life." How can we weave together the three fundamental dimensions of human existence: our physical being, psychological experience, and spiritual essence?', author: '— David Boadella, "Lifestreams"' },
    },

    forWho: {
      title: 'Who Is Somatic Psychotherapy For?',
      intro1: 'Somatic psychotherapy offers an experience in which, beyond words, we attend to everything arising in the body — as a full partner in the process of processing, balancing, and regulating. A relationship built on trust, attentiveness to what is happening in the body and the space, and movement in the directions that open up — all of this allows progress toward places that words alone sometimes cannot reach.',
      intro2: 'Therapy is suited to anyone who feels that various emotional, mental, or physical phenomena are running their life in the wake of difficult experiences and life events — whether it was a single acute incident or an ongoing struggle; whether it happened early or later in life; and whether the source of these feelings is fully known or remains vague, confusing, and unexplained.',
      challengesTitle: 'Challenges We Meet in the Clinic',
      challengesSub: 'If your body or mind have signaled that it is time to pause and explore — or to go deeper — these are the main challenges and themes we can address together:',
      dailyLabel: 'How can this be experienced day to day?*',
      disclaimer: '* Varies from person to person.',
      notFound: 'If you did not find your topic in the above, feel free to write and we can explore it together.',
      processTitle: 'Process Structure & Expectations',
      process1: 'If this is your first time entering the space of therapy, it is important to know that every process is unique and personally tailored to you and your needs. Depending on the challenge or topic, therapy may be short-term (up to six months) or long-term.',
      process2: 'The approach that guides me is built on creating a therapeutic relationship characterized by trust, respect, and curiosity. Together — and sometimes with courage — we will work toward the goals you came with. The first session and those that follow are an opportunity for initial acquaintance, asking questions, and jointly exploring whether working together feels right and fitting for you.',
      quote: { text: 'Maybe it\'s not a happy story. But it\'s real and it\'s mine.', author: '— from "Emotional Inheritance" by Galit Atlas' },
      ctaText: 'Choosing therapy means taking a step toward a full and present human existence — grounded in the understanding that being a grown adult in this world is a process that takes time, consent, and initiation.',
      ctaBtn: 'Get in Touch',
      challenges: [
        { num: '1', title: 'Stress, Anxiety & Hypervigilance', body: 'When the nervous system operates under prolonged overload or carries the imprint of a turbulent past event, anxiety and vigilance stop being merely "thoughts" and become a permanent existential state that governs the body.', daily: 'Chronic inner restlessness, intense startle responses to small sounds or stimuli, raised and rigid shoulders, short or shallow breath, racing heartbeat, a sense of threat, sudden flooding or pressure in the chest that makes it hard to let go, relax, or sleep.' },
        { num: '2', title: 'Sadness, Withdrawal & Loss of Vitality', body: 'Sometimes, to protect ourselves from pain, fear, or flooding that was more than the system could bear, body and mind contract and withdraw — leading to a sense of being stuck and a reduction in natural vitality.', daily: 'A feeling of emptiness, a dark physical heaviness in the limbs (as if enormous effort is required just to move), a tendency to disconnect from surroundings or from the body under stress (dissociation), emotional and sensory numbness, lack of physical warmth, a slack or blank gaze or posture.' },
        { num: '3', title: 'Grief & Loss', body: 'Deep grief and the loss of a loved one, a relationship, or a meaningful life phase — occurring in a world that keeps moving — alters the system we live within. Sometimes it is difficult to touch these contents; they feel volatile or dangerous.', daily: 'A sense of emptiness, physical heaviness in the chest or limbs, existential questions, loss of meaning or worth, the experience of time standing still while the world continues to move normally, difficulty crying or feeling emotions.' },
        { num: '4', title: 'Relational Difficulties, Boundaries & Connection', body: 'The way we connect with the world is directly tied to our physical and energetic boundaries — our capacity to remain in contact with ourselves while in contact with another, especially if those boundaries were breached or damaged in the past.', daily: 'A feeling of being "swallowed," high vigilance or a sense of "disappearing" within a relationship or before authority figures, physical difficulty saying "no" (a sense of choking or constriction in the throat), or alternatively building rigid walls that lead to isolation.' },
        { num: '5', title: 'Emotional & Physical Symptoms', body: 'The body often "speaks," perpetuating accidents, injuries, or difficult emotional experiences from the past through symptoms, chronic pain, or shifting sensations of distress — without a clear medical solution or explanation.', daily: 'Pains labeled psychosomatic, persistent physical symptoms, a significant shift in self-perception, numbness, flashback experiences.' },
        { num: '6', title: 'Life Crises & Medical Crises', body: 'A sudden encounter with illness, injury, or a dramatic change in health status can create a medical trauma that shakes the basic sense of control and safety in the world, and surfaces large existential questions.', daily: 'A deep experience of bodily betrayal, existential fear about the future, helplessness in the body\'s functioning, difficulty and tension in adjusting to new limitations imposed by accident, injury, or illness.' },
        { num: '7', title: 'Growth, Depth & Connection to Aliveness', body: 'Seeking therapy does not have to arise only from acute crisis. Sometimes the impulse to begin a process comes from a deep inner desire to slow the automatic pace of life, to know oneself, and to live more fully.', daily: 'A vague sense of being stuck in daily life, a constant "autopilot" and lack of vitality, alongside a quiet inner drive seeking to deepen, explore, and follow natural curiosity and impulse. A longing for inner authority and groundedness in the world.' },
      ],
    },

    faq: {
      title: 'Frequently Asked Questions',
      quote: { text: 'If I were to try to summarize what a therapeutic stance is, a large part of it is teaching you to be deeply respectful of the complexity of your own mind; to understand that it is not exactly something that is obvious to you.', author: '— paraphrased from Alain de Botton, on why one might seek therapy, from an interview' },
      items: [
        { q: 'What exactly is somatic psychotherapy?', a: 'Somatic psychotherapy (and in particular the Biosynthesis approach) begins from the premise that body and mind are one. For example, when someone does something that makes us angry, we tend to think about how irritating they are, find it hard to focus on anything else, and simultaneously feel heat and high tension spreading through the body.\n\nPast and present events, crises, and tensions are not stored only as mental memory — they leave an imprint on the nervous system, in muscle tissue, and in breathing patterns. In sessions, alongside conversation and the relationship that builds, we turn attention toward what is happening beneath the words. Through breath, imagination, movement, and sometimes touch, we discover the pathway that is accessible and available for you, reaching places that speech alone cannot.' },
        { q: 'Does therapy require touch?', a: 'Absolutely not. The Biosynthesis approach allows for the use of conscious and respectful touch as a working tool, but this is not a necessary condition for a successful process — as can be seen from complete therapeutic processes conducted entirely online. Any work involving touch takes place only with your full and explicit consent, and depends entirely on personal preference and the boundaries of both parties in the encounter. If there is reluctance or a preference to work without touch at all, the process will unfold fully through conversation, attentiveness, breath, and movement in the room.' },
        { q: 'What does a therapy session at the clinic look like in practice?', a: 'Sessions have no rigid protocol. Through dialogue and deep listening, we can approach the topics you arrived with that day, or continue deepening a theme we have been exploring over time. Through the Biosynthesis approach, we will clarify, inquire, question, check, experiment, and discover what is calling for attention.\n\nAccordingly, we will meet together with open questions, ancient fears, moving revelations, recurring patterns, pains that still hurt and those that have healed — alongside interesting and new movements. We move at the pace that suits your system, without creating overwhelm or pushing beyond your capacity. We do not break through defenses.' },
        { q: 'How long does therapy last, and what is the difference between a short and long process?', a: 'The duration of the process flows directly from the request and the goals you arrived with, and we align expectations around this from the very first sessions:\n\nFocused, short-term process (up to six months): Generally suited to navigating a specific crisis, a sudden change, or a particular life crossroads. The focus is on acquiring practical somatic tools for regulation, establishing anchors, and restoring a sense of groundedness and safety.\n\nIn-depth, long-term process (one year or more): Suited when the request touches on chronic ongoing patterns, dramatic events that left a significant mark, complex trauma, deep difficulties in relationships, or a profound desire for self-inquiry.\n\nThe process ends at your request and when there is a sense of readiness — always through shared reflection and conversation.' },
        { q: 'What happens in the first session?', a: 'The first session is devoted to initial acquaintance and beginning to build a safe space. It is an invitation for you to bring your story, raise questions and concerns, and share the challenges that led you to seek therapy. For me, it is an opportunity to be present and listen to your world, offer reflections, and explore together whether my therapeutic approach might suit you.\n\nThere is no commitment to continuing beyond this session simply by attending, but I suggest we regard the first four sessions as a phase designed for making contact, building trust, and mutual exploration.' },
        { q: 'What is Biosynthesis and is it professionally recognized?', a: 'Biosynthesis is a well-established and recognized approach to somatic-analytic psychotherapy, founded over 45 years ago by David Boadella. The name means "integration of life," and it is grounded in creating renewed connection and balance among the three fundamental dimensions of our existence: physical being, psychological experience, and spiritual essence.\n\nThe approach is based on scientifically grounded research in neurobiology and embryology (fetal development). It is officially recognized by the European Association for Psychotherapy (EAP) and the European Association for Body Psychotherapy (EABP). I trained in Israel at the School for Psychotherapy in the Biosynthesis Approach, and my certification was accredited by the International Institute for Biosynthesis in Switzerland (IIBS). My clinical work is conducted under ongoing professional supervision.' },
        { q: 'I noticed you also work with community grief rituals. How does that connect to individual therapy?', a: 'Grief and sorrow are not pathology, "illness," or a problem to be fixed or erased. They are an inseparable part of being in the world as maturing, growing, initiated human beings.\n\nMy connection to these worlds expands the lens inside the room: the therapeutic process is always connected to the broader contexts of life — from family history, culture, and the relationships that shaped you. The connection between ritual technology and somatic work allows us to give grief and pain "a form in the world," as humans have always done.' },
      ],
    },

    writings: {
      title: 'Seasonal Inspiration — Gathered or Written',
    },

    about: {
      title: 'About Me',
      paragraphs: [
        'Hello, I am Dor. The name I chose for the clinic, "To Be Human," was born from a long contemplation of the fact that being a grown adult in this world is an ongoing process — one that takes time, requires initiation, and contains within it a wide range of experiences. My professional path came into being through deep personal and professional inquiry and processing that began about 11 years ago, and led me to explore the ways in which body and mind meet and are interconnected. Following meaningful military service, I set out on a journey of exploration, discovery, and experience.',
        'Since 2017, I have been accompanying adults in the clinic through processes of change, coping, and growth from crisis — individually, face to face, and online. My professional path began through work with therapeutic yoga (I later also served as a teaching assistant in practitioner and teacher training in this field). I specialized in and worked with rehabilitation from injuries and trauma, chronic pain, autoimmune conditions, and emotional and somatic regulation.',
        'From 2022, I have been working as a somatic psychotherapist in the Biosynthesis approach, certified by the International Institute in Switzerland (IIBS). My connection to Biosynthesis arose from the fact that it adapts itself to the person, not the other way around. It is grounded in re-establishing balance among different parts of you, and allows movement from distress toward natural resources and vitality. I am currently part of the teaching faculty as a teaching assistant at the School for Biosynthesis in Israel, and have recently begun training as a Supervisor within the approach. My therapeutic process in the private clinic is conducted under ongoing professional supervision, within the frame of deep, long-term processes.',
        'My work in the therapy room is connected to the broader contexts of life. In therapy we take into account your personal story and the relational contexts of your life, from the understanding that we are always connected to the people, stories, and places that shaped us — even if we, or they, are no longer there. This understanding also accompanies me personally: over the past decade I have been researching and reconstructing the family story of my ancestors, who came from Eastern Europe, through locating documents in archives and working with family constellation.',
        'The wide-angle view and this kinship with the roots from which people grow led me into the world of grief rituals, life, and death. I was ordained as a facilitator in the "Grief as Gateway to Life" program, inspired by the work of Francis Weller, and I draw ongoing inspiration from the teachings of Stephen Jenkinson and Alejandro Jodorowsky. I currently serve as a team member in community grief rituals, from the understanding that grief and sorrow are not pathology to be fixed, but an inseparable part of the process of human initiation and maturation. In my view, rituals are necessary human technologies for our time.',
        'Over the years I have initiated and built projects that integrate body and community: I established "Zuzu" — a space for alternative movement events that allows free personal expression — and was a co-founder of "Bodyfulness" (a wellness initiative for organizations).',
        'Outside the clinic, my own inquiry is accompanied by daily connection to the earth and to creation: I am learning about connection to the land through small-scale productive agriculture, fermenting vegetables and preserving food, exploring movement focused on fascial tissue, and finding anchor and inspiration in music, song, and the wonderful language of otherness — in which and through which we live.',
        'To our therapeutic encounters I bring qualities of deep listening, presence, curiosity, discernment, and humor. The central intention that guides me is to build together with you a therapeutic relationship that holds human meeting at eye level, mutual trust, respect, and a precise pace that fits you and the unique contexts of your life.',
      ],
      quote: { text: 'I thought I wanted to be a poet, but deep in my heart — I simply wanted to be a poem.', author: '— Jaime Gil de Biedma' },
    },

    contact: {
      title: 'Ways to Get in Touch',
      nameLbl: 'Name',
      namePh: 'Your name',
      phoneLbl: 'Phone',
      phonePh: 'Your phone number',
      emailLbl: 'Email',
      emailPh: 'Your email address',
      msgLbl: 'Message',
      msgPh: 'How can I help?',
      sending: 'Sending...',
      send: 'Send',
      successTitle: 'Message sent, thank you!',
      successSub: 'I will get back to you soon.',
      contactMethodsLabel: 'Other ways to connect',
      calendlyBtn: '📅 Schedule a time in my digital calendar',
      waBtn: '💬 Send a WhatsApp message',
      locationLabel: 'Location',
      locationText: 'The clinic is located in Beit Oren. Upon arrival for the first session, I will guide you on where to park and exactly where we meet.',
    },

    accessibility: {
      title: 'Accessibility in the Therapeutic Space',
      intro: 'An inseparable part of creating a safe and welcoming therapeutic space for everyone is the aspiration to enable full access, adapted to the diverse needs of those who come to the clinic.',
      s1Title: 'Physical & Spatial Access',
      s1p1: 'Location & Access: The clinic in Beit Oren is located on the ground floor, with direct access and no stairs. The space is accessible and adapted for wheelchair users.',
      s1p2: 'Parking: Close to the building entrance (60–70 m) there is a dedicated parking space for people with disabilities.',
      s1p3: 'If you need to arrange specific physical accessibility or accompanying support upon arrival, please contact me in advance so we can prepare appropriately.',
      s2Title: 'Accommodations & Special Needs',
      s2p1: 'If you have visual or hearing impairments, sensory sensitivities, or other special needs not listed here, I invite you to mention this in your initial inquiry or during our phone call, so that we can adapt the nature of our sessions and the space to suit you.',
      s3Title: 'Remote Sessions (Online Therapy)',
      s3p1: 'For people dealing with mobility limitations, difficulty traveling, or for those who live at a distance (including those living abroad), are in transitional periods or traveling, or simply prefer to meet in their home environment — the therapeutic process can be conducted fully online.',
      s3p2: 'Required conditions: To enable the work, you will need a computer with a camera and a reliable internet connection, as well as a quiet, comfortable, and safe environment where you can speak and move freely without interruption.',
      ctaTitle: 'Contact & Consultation',
      ctaText: 'If you have special needs or questions about accessibility that were not addressed on this page, please do not hesitate to reach out by call or message with details of the points important to you. I am committed to preparing a safe and accessible therapeutic space for everyone, and together we will find the most suitable arrangement for you.',
    },
  },
};